const moment = require("moment");
const createdAt = moment().unix();
const updatedAt = moment().unix();
module.exports = [
  {
    name: "Samim",
    email: "samim@test.pk",
    gender: "male",
    status: "active",
    phone: "03068099788",
    createdAt,
    updatedAt,
  },
  {
    name: "Bilal",
    email: "Bilal@test.pk",
    gender: "male",
    status: "offline",
    phone: "03168293538",
    createdAt,
    updatedAt,
  },
  {
    name: "Tariq",
    email: "Tariq@test.pk",
    gender: "male",
    status: "active",
    phone: "034521223",
    createdAt,
    updatedAt,
  },
  {
    name: "Emma Jones",
    email: "emma.jones@example.com",
    gender: "female",
    status: "active",
    phone: "+1-202-555-0111",
    createdAt,
    updatedAt,
  },
  {
    name: "John Smith",
    email: "john.smith@example.com",
    gender: "male",
    status: "inactive",
    phone: "+1-202-555-0222",
    createdAt,
    updatedAt,
  },
  {
    name: "Emily Davis",
    email: "emily.davis@example.com",
    gender: "female",
    status: "active",
    phone: "+1-202-555-0333",
    createdAt,
    updatedAt,
  },
  {
    name: "William Brown",
    email: "william.brown@example.com",
    gender: "male",
    status: "inactive",
    phone: "+1-202-555-0444",
    createdAt,
    updatedAt,
  },
  {
    name: "Olivia Wilson",
    email: "olivia.wilson@example.com",
    gender: "female",
    status: "active",
    phone: "+1-202-555-0555",
    createdAt,
    updatedAt,
  },
  {
    name: "John Doe",
    email: "john.doe@example.com",
    gender: "male",
    status: "active",
    phone: "1234567890",
    createdAt,
    updatedAt,
  },
  {
    name: "Jane Smith",
    email: "jane.smith@example.com",
    gender: "female",
    status: "active",
    phone: "9876543210",
    createdAt,
    updatedAt,
  },
  {
    name: "David Johnson",
    email: "david.johnson@example.com",
    gender: "male",
    status: "active",
    phone: "5555555555",
    createdAt,
    updatedAt,
  },
  {
    name: "Emily Davis",
    email: "emily.davis@example.com",
    gender: "female",
    status: "inactive",
    phone: "9999999999",
    createdAt,
    updatedAt,
  },
  {
    name: "Michael Wilson",
    email: "michael.wilson@example.com",
    gender: "male",
    status: "active",
    phone: "7777777777",
    createdAt,
    updatedAt,
  },
  {
    name: "Olivia Martinez",
    email: "olivia.martinez@example.com",
    gender: "female",
    status: "active",
    phone: "1111111111",
    createdAt,
    updatedAt,
  },
  {
    name: "James Anderson",
    email: "james.anderson@example.com",
    gender: "male",
    status: "inactive",
    phone: "2222222222",
    createdAt,
    updatedAt,
  },
  {
    name: "Sophia Clark",
    email: "sophia.clark@example.com",
    gender: "female",
    status: "active",
    phone: "3333333333",
    createdAt,
    updatedAt,
  },
  {
    name: "Daniel Thomas",
    email: "daniel.thomas@example.com",
    gender: "male",
    status: "active",
    phone: "4444444444",
    createdAt,
    updatedAt,
  },
  {
    name: "Ava Lewis",
    email: "ava.lewis@example.com",
    gender: "female",
    status: "active",
    phone: "6666666666",
    createdAt,
    updatedAt,
  },
];
